# Generated by Django 5.0.6 on 2026-06-03 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('kind', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Phone call'), ('sms', 'SMS')], default='whatsapp', help_text='Communication channel.', max_length=20)),
                ('direction', models.CharField(choices=[('in', 'Inbound (from customer)'), ('out', 'Outbound (to customer)')], default='out', help_text='Whether this message was sent TO or received FROM the customer.', max_length=5)),
                ('body', models.TextField(help_text='Message text or call summary.')),
                ('who', models.CharField(default='', help_text="Sender name, e.g. 'Hamisi M.' or 'auto-reminder'.", max_length=100)),
            ],
            options={
                'verbose_name': 'Credit Message',
                'verbose_name_plural': 'Credit Messages',
                'db_table': 'credits_creditmessage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('body', models.TextField(help_text='Note content.')),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
                'db_table': 'credits_creditnote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('amount', models.PositiveIntegerField(help_text='Payment amount (TZS).')),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Bank', 'Bank transfer'), ('Tigo Pesa', 'Tigo Pesa')], default='Cash', help_text='Payment method used.', max_length=20)),
                ('reference', models.CharField(blank=True, default='', help_text='Payment reference (M-Pesa code, bank ref, etc.).', max_length=100)),
                ('note', models.TextField(blank=True, default='', help_text="Optional note (e.g. 'Partial payment, rest next week').")),
            ],
            options={
                'verbose_name': 'Credit Payment',
                'verbose_name_plural': 'Credit Payments',
                'db_table': 'credits_creditpayment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('amount', models.PositiveIntegerField(help_text='Total amount of the credit sale (TZS).')),
                ('amount_paid', models.PositiveIntegerField(default=0, help_text='Total amount paid towards this tab so far (TZS, cached).')),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_paid', 'Partially paid'), ('settled', 'Settled'), ('written_off', 'Written off')], default='open', help_text='Current status of this credit tab.', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Date by which payment is expected.', null=True)),
                ('write_off_reason', models.TextField(blank=True, default='', help_text='Reason for writing off this tab (if applicable).')),
                ('till_number', models.CharField(blank=True, default='Till #1', help_text='Register/till where credit was issued.', max_length=20)),
            ],
            options={
                'verbose_name': 'Credit Tab',
                'verbose_name_plural': 'Credit Tabs',
                'db_table': 'credits_credittab',
                'ordering': ['-created_at'],
            },
        ),
    ]
