# Generated by Django 5.0.6 on 2026-06-03 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('credits', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditmessage',
            name='customer',
            field=models.ForeignKey(help_text='Customer involved in this communication.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_messages', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='creditmessage',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='Staff user who sent/logged this (null for auto-reminders).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditmessage',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_messages', to='accounts.store'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='by',
            field=models.ForeignKey(blank=True, help_text='Staff member who wrote this note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='customer',
            field=models.ForeignKey(help_text='Customer this note is about.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='accounts.store'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='cashier',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='customer',
            field=models.ForeignKey(help_text='Customer making this payment.', on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='store',
            field=models.ForeignKey(help_text='Store where the payment was recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_payments', to='accounts.store'),
        ),
        migrations.AddField(
            model_name='credittab',
            name='cashier',
            field=models.ForeignKey(blank=True, help_text='Cashier who created this credit tab.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_tabs_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credittab',
            name='customer',
            field=models.ForeignKey(help_text='Customer who bought on credit.', on_delete=django.db.models.deletion.PROTECT, related_name='credit_tabs', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='credittab',
            name='store',
            field=models.ForeignKey(help_text='Store where the credit was issued.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_tabs', to='accounts.store'),
        ),
    ]
