# Generated by Django 5.0.6 on 2026-06-03 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittab',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='POS transaction that created this credit tab.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_tab', to='transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['customer', 'created_at'], name='idx_creditpay_cust_date'),
        ),
        migrations.AddIndex(
            model_name='credittab',
            index=models.Index(fields=['customer', 'status'], name='idx_credittab_cust_status'),
        ),
        migrations.AddIndex(
            model_name='credittab',
            index=models.Index(fields=['store', 'status'], name='idx_credittab_store_status'),
        ),
        migrations.AddIndex(
            model_name='credittab',
            index=models.Index(fields=['due_date'], name='idx_credittab_due_date'),
        ),
    ]
