# Generated by Django 5.0.6 on 2026-06-03 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('name', models.CharField(help_text="Customer's full name.", max_length=200)),
                ('phone', models.CharField(blank=True, default='', help_text='Phone in international format, e.g. +255 712 345 678.', max_length=30)),
                ('email', models.EmailField(blank=True, default='', help_text='Email address (optional).', max_length=254)),
                ('segment', models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular'), ('Occasional', 'Occasional'), ('New', 'New')], default='New', help_text='Loyalty segment assigned to this customer.', max_length=20)),
                ('total_spent', models.PositiveIntegerField(default=0, help_text='Lifetime total amount spent by this customer (TZS, cached).')),
                ('last_visit', models.DateField(blank=True, help_text='Date of last completed transaction.', null=True)),
                ('avg_ticket', models.PositiveIntegerField(default=0, help_text='Average transaction total (TZS, cached).')),
                ('open_credit', models.PositiveIntegerField(default=0, help_text='Current outstanding credit balance (TZS, cached).')),
                ('avatar_hue', models.PositiveSmallIntegerField(default=200, help_text='0–360 colour hue for avatar gradient.')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes about this customer.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive customers are hidden from lists but not deleted.')),
                ('store', models.ForeignKey(help_text='Store this customer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers_customer',
                'ordering': ['-total_spent'],
                'indexes': [models.Index(fields=['store', 'is_active'], name='idx_customer_store_active'), models.Index(fields=['segment'], name='idx_customer_segment')],
                'unique_together': {('store', 'phone')},
            },
        ),
    ]
