# Generated by Django 5.0.6 on 2026-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum credit allowed (TZS). Null means no limit.', null=True),
        ),
    ]
