# Generated by Django 5.0.6 on 2026-06-03 07:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('name', models.CharField(help_text="Trading/shop name of the organisation, e.g. 'Duka Kuu'.", max_length=200)),
                ('legal_name', models.CharField(blank=True, help_text='Full legal registered name (may differ from trading name).', max_length=300)),
                ('tin', models.CharField(blank=True, help_text='Tanzania TRA Tax Identification Number (printed on receipts).', max_length=50, verbose_name='TIN')),
                ('business_type', models.CharField(choices=[('pharmacy', 'Pharmacy (Duka la Dawa)'), ('retail', 'Retail Shop (Duka la Rejareja)'), ('wholesale', 'Wholesale (Jumla)')], default='retail', help_text='Type of business (determines pre-configured POS categories).', max_length=20)),
                ('region', models.CharField(blank=True, choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa'), ('Kagera', 'Kagera'), ('Katavi', 'Katavi'), ('Kigoma', 'Kigoma'), ('Kilimanjaro', 'Kilimanjaro'), ('Lindi', 'Lindi'), ('Manyara', 'Manyara'), ('Mara', 'Mara'), ('Mbeya', 'Mbeya'), ('Morogoro', 'Morogoro'), ('Mtwara', 'Mtwara'), ('Mwanza', 'Mwanza'), ('Njombe', 'Njombe'), ('Pemba North', 'Pemba North'), ('Pemba South', 'Pemba South'), ('Pwani', 'Pwani'), ('Rukwa', 'Rukwa'), ('Ruvuma', 'Ruvuma'), ('Shinyanga', 'Shinyanga'), ('Simiyu', 'Simiyu'), ('Singida', 'Singida'), ('Songwe', 'Songwe'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga'), ('Unguja North', 'Unguja North'), ('Unguja South', 'Unguja South'), ('Unguja West', 'Unguja West')], help_text='Tanzania region where this business is based.', max_length=100)),
                ('country', models.CharField(default='TZ', help_text='ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('currency', models.CharField(default='TZS', help_text='ISO 4217 currency code.', max_length=3)),
                ('max_stores', models.PositiveSmallIntegerField(default=3, help_text='Maximum stores allowed. Updated by subscription system when extra stores are purchased.')),
                ('ai_credits_monthly', models.PositiveIntegerField(default=5000, help_text='Total AI credits allocated per month.')),
                ('plan', models.CharField(choices=[('free', 'Free / Trial'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', help_text='Subscription plan tier. Synced by the subscription system.', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='Trial expiry datetime (set on registration, null after upgrade).', null=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('name', models.CharField(help_text="Store name shown in the UI, e.g. 'Kariakoo Branch'.", max_length=200)),
                ('code', models.CharField(blank=True, help_text="Short store code for transaction IDs, e.g. 'KRC' → TXN-KRC-2043.", max_length=10)),
                ('address', models.TextField(blank=True, help_text='Full physical address of the store.')),
                ('area', models.CharField(blank=True, help_text="Area / neighbourhood, e.g. 'Kariakoo'.", max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Store contact phone number.', max_length=30)),
                ('till_count', models.PositiveSmallIntegerField(default=1, help_text='Number of POS tills/registers in this store.')),
                ('email', models.EmailField(blank=True, help_text='Store contact email address.', max_length=254)),
                ('open_hours', models.CharField(blank=True, default='7:00 AM – 9:00 PM', help_text='Opening hours label shown in the UI.', max_length=50)),
                ('color', models.CharField(blank=True, default='#6366f1', help_text='Hex colour for store avatar and sparkline.', max_length=20)),
                ('is_main_store', models.BooleanField(default=False, help_text='True for the primary store created during registration.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('paused', 'Paused')], default='open', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Active stores appear in the store switcher.')),
                ('organisation', models.ForeignKey(help_text='Organisation this store belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['organisation__name', 'name'],
                'unique_together': {('organisation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin (Cameltech)'), ('owner', 'Owner'), ('staff', 'Staff')], default='staff', help_text='User role determines API access level.', max_length=20)),
                ('phone', models.CharField(help_text='10-digit Tanzanian phone number used to log in (e.g. 0712345678).', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number (e.g. 0712345678).', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, default=None, help_text='Optional email address. Must be unique if provided.', max_length=254, null=True, unique=True)),
                ('avatar_hue', models.PositiveSmallIntegerField(default=260, help_text='Hue (0–360) for avatar background gradient.')),
                ('shift', models.CharField(choices=[('morning', 'Morning (7am–2pm)'), ('evening', 'Evening (2pm–9pm)'), ('full_day', 'Full day (7am–7pm)'), ('weekend', 'Weekend (Sat–Sun)')], default='morning', max_length=20)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('pin', models.CharField(blank=True, help_text='4-digit POS access PIN.', max_length=4)),
                ('can_refund', models.BooleanField(default=False)),
                ('can_discount', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False, help_text='True after the owner confirms their phone number via OTP.')),
                ('is_email_verified', models.BooleanField(default=False, help_text='True after the owner confirms their email address.')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organisation', models.ForeignKey(blank=True, help_text='Direct organisation link set for owner-role users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.organisation')),
                ('store', models.ForeignKey(blank=True, help_text='Primary store this user works at. Required for staff, optional for owners.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='accounts.store')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AICredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('used', models.PositiveIntegerField(default=0)),
                ('allocated', models.PositiveIntegerField(default=5000)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credits', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'AI Credit',
                'verbose_name_plural': 'AI Credits',
                'ordering': ['-year', '-month'],
                'unique_together': {('organisation', 'year', 'month')},
            },
        ),
    ]
