# Generated by Django 5.0.6 on 2026-06-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='vat_enabled',
            field=models.BooleanField(default=True, help_text='Whether this store charges VAT (18% TRA). Disable for stores not VAT-registered.'),
        ),
    ]
