# Generated by Django 5.0.6 on 2026-07-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_vat_enabled_to_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='sendafrica_api_key',
            field=models.CharField(blank=True, help_text="SendAfrica API key (starts with 'SA-'). Pasted by the owner in Settings → Integrations.", max_length=200),
        ),
        migrations.AddField(
            model_name='organisation',
            name='sms_sender_id',
            field=models.CharField(blank=True, help_text="Approved custom SMS sender ID. Falls back to 'SendAfrika' if unset or unapproved.", max_length=20),
        ),
    ]
