# Generated by Django 5.0.6 on 2026-06-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_vat_enabled_to_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.UUIDField(
                blank=True, help_text="One-time token for password reset.", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_expires",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiry time for the password reset token.",
                null=True,
            ),
        ),
    ]
