# Generated by Django 5.0.6 on 2026-07-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organisation_sendafrica_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ngamia_api_key',
            field=models.CharField(blank=True, help_text="Personal Ngamia API key (starts with 'ngm_'). Used once the free monthly AI credits run out.", max_length=200),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ai_credits_monthly',
            field=models.PositiveIntegerField(default=500, help_text='Total free AI credits allocated per month (platform-funded via Ngamia).'),
        ),
    ]
