# Generated by Django 5.2.14 on 2026-06-02 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('title', models.CharField(help_text='Short note title shown in the note card header.', max_length=300)),
                ('content', models.TextField(blank=True, help_text='Full note body — shown in the edit modal and previewed (2 lines) on the card.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tag list, e.g. ["Suppliers", "Ideas"]. Used for folder filtering in the UI.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created the note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(help_text='Organisation (for multi-store queries).', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.organisation')),
                ('store', models.ForeignKey(help_text='Store this note belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='notebook_no_store_i_414316_idx')],
            },
        ),
    ]
