"""
apps/analytics/admin.py

Django Admin for the DailySummary model.
Provides a read-only view of pre-aggregated analytics data.
"""

from django.contrib import admin
from django.utils.html import format_html

from .models import DailySummary


@admin.register(DailySummary)
class DailySummaryAdmin(admin.ModelAdmin):
    """
    Read-only admin view for daily analytics summaries.
    Useful for debugging and verifying aggregate integrity.
    """

    list_display = [
        "date", "store",
        "transaction_count", "customer_count",
        "revenue_display", "profit_display", "margin_display",
        "cash_display", "mpesa_display", "credit_display",
    ]
    list_display_links = ["date"]
    list_filter = ["store", "date"]
    date_hierarchy = "date"
    ordering = ["-date"]
    list_select_related = ["store"]

    readonly_fields = [
        "id", "store", "date",
        "transaction_count", "customer_count",
        "revenue", "credit_revenue", "cost_total", "profit", "tax_collected", "refund_total",
        "cash_revenue", "mpesa_revenue", "tigo_revenue", "bank_revenue", "credit_issued",
        "created_at", "updated_at",
    ]

    def has_add_permission(self, request):
        """Summaries are generated by the system, not manually."""
        return False

    def has_delete_permission(self, request, obj=None):
        """Do not allow deleting summaries (use rebuild command instead)."""
        return False

    def revenue_display(self, obj):
        return f"TZS {obj.revenue:,}"
    revenue_display.short_description = "Revenue"
    revenue_display.admin_order_field = "revenue"

    def profit_display(self, obj):
        color = "#22c55e" if obj.profit >= 0 else "#ef4444"
        return format_html('<span style="color:{}">TZS {:,}</span>', color, obj.profit)
    profit_display.short_description = "Profit"

    def margin_display(self, obj):
        pct = obj.margin_pct
        color = "#22c55e" if pct >= 20 else "#f59e0b" if pct >= 10 else "#ef4444"
        return format_html('<span style="color:{}">{}%</span>', color, pct)
    margin_display.short_description = "Margin"

    def cash_display(self, obj):
        return f"TZS {obj.cash_revenue:,}"
    cash_display.short_description = "Cash"

    def mpesa_display(self, obj):
        return f"TZS {obj.mpesa_revenue:,}"
    mpesa_display.short_description = "M-Pesa"

    def credit_display(self, obj):
        return f"TZS {obj.credit_issued:,}"
    credit_display.short_description = "Credit"
