# Generated by Django 5.0.6 on 2026-06-03 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('name', models.CharField(help_text="Display name shown to owners, e.g. 'Monthly' or '6-Month Package'.", max_length=100)),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'monthly', 'half-yearly', 'yearly'.", unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional marketing description of this plan.')),
                ('price_per_month', models.PositiveIntegerField(help_text='Monthly price in TZS, e.g. 25000 for 25,000 TZS/month.')),
                ('duration_months', models.PositiveSmallIntegerField(default=1, help_text='Number of months this plan covers per payment cycle.')),
                ('included_stores', models.PositiveSmallIntegerField(default=3, help_text='Number of stores included in the base price.')),
                ('extra_store_price_per_month', models.PositiveIntegerField(default=12000, help_text='Cost per additional store per month, in TZS.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active plans are shown to prospective owners.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = shown first).')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', 'price_per_month'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending_payment', 'Pending Payment')], default='pending_payment', max_length=20)),
                ('start_date', models.DateField(help_text='Subscription start date.')),
                ('end_date', models.DateField(help_text='Subscription end date (access expires at midnight).')),
                ('is_trial', models.BooleanField(default=False, help_text='True if this is the initial 1-week trial subscription.')),
                ('trial_fee', models.PositiveIntegerField(default=10000, help_text='One-time trial fee in TZS (default 10,000).')),
                ('extra_stores', models.PositiveSmallIntegerField(default=0, help_text="Number of additional paid stores beyond the plan's bundled quota.")),
                ('amount_paid', models.PositiveIntegerField(default=0, help_text='Amount actually received in TZS.')),
                ('payment_reference', models.CharField(blank=True, help_text='M-Pesa code, bank ref, or other payment identifier.', max_length=200)),
                ('payment_date', models.DateField(blank=True, help_text='Date the payment was received.', null=True)),
                ('notes', models.TextField(blank=True, help_text="Internal notes (e.g. 'payment confirmed via WhatsApp').")),
                ('activated_by', models.ForeignKey(blank=True, help_text='Cameltech admin who confirmed the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(help_text='The organisation this subscription belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.organisation')),
                ('plan', models.ForeignKey(blank=True, help_text='The plan tier chosen. Null during trial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='subscriptio_organis_91dbf8_idx'), models.Index(fields=['end_date'], name='subscriptio_end_dat_60694b_idx')],
            },
        ),
    ]
