# Generated by Django 5.0.6 on 2026-06-03 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('txn_number', models.CharField(help_text='Human-readable transaction number (TXN-NNNN) shown on receipts.', max_length=30, unique=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Tigo Pesa', 'Tigo Pesa'), ('Bank', 'Bank'), ('Credit', 'Credit (on tab)')], default='Cash', help_text='How the customer paid.', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Mobile money confirmation code or bank reference.', max_length=100)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('credit', 'On Credit'), ('refunded', 'Refunded'), ('void', 'Void')], default='paid', help_text='Transaction status.', max_length=20)),
                ('subtotal', models.PositiveIntegerField(default=0, help_text='Sum of all line totals before discount (TZS).')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage applied (e.g. 5.00 for 5%).', max_digits=5)),
                ('discount_amount', models.PositiveIntegerField(default=0, help_text='Absolute discount amount in TZS.')),
                ('tax_amount', models.PositiveIntegerField(default=0, help_text='VAT (18%) amount in TZS.')),
                ('total', models.PositiveIntegerField(default=0, help_text='Net total charged to customer (TZS).')),
                ('cost_total', models.PositiveIntegerField(default=0, help_text='Total cost of goods sold (TZS).')),
                ('profit', models.IntegerField(default=0, help_text='Gross profit on this transaction (TZS). Can be negative.')),
                ('till_number', models.CharField(default='Till #1', help_text="Till / register number, e.g. 'Till #2'.", max_length=20)),
                ('customer_name', models.CharField(default='Walk-in', help_text="Customer display name (or 'Walk-in' if anonymous).", max_length=200)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone number (+255 7XX XXX XXX).', max_length=30)),
                ('channel', models.CharField(choices=[('counter', 'Counter')], default='counter', help_text='Sales channel (counter, mobile, online, etc.).', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes (e.g. refund reason).')),
                ('cashier', models.ForeignKey(blank=True, help_text='Staff member who processed this sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Linked customer profile (null for walk-in customers).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customers.customer')),
                ('store', models.ForeignKey(help_text='Store where this sale took place.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('product_name', models.CharField(help_text='Product name at time of sale (snapshot).', max_length=300)),
                ('product_sku', models.CharField(help_text='Product SKU at time of sale (snapshot).', max_length=50)),
                ('unit_price', models.PositiveIntegerField(help_text='Selling price per unit at time of sale (TZS).')),
                ('unit_cost', models.PositiveIntegerField(default=0, help_text='Cost per unit at time of sale (TZS).')),
                ('qty', models.PositiveIntegerField(default=1, help_text='Quantity sold.')),
                ('product', models.ForeignKey(blank=True, help_text='Product sold (null if product was later deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_lines', to='inventory.product')),
                ('transaction', models.ForeignKey(help_text='Parent transaction this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Line',
                'verbose_name_plural': 'Transaction Lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['store', 'created_at'], name='transaction_store_i_2e6cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_71abbb_idx'),
        ),
    ]
