# Generated by Django 5.0.6 on 2026-06-14 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_vat_enabled_to_store'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxnSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('last_number', models.PositiveIntegerField(default=1000, help_text='Last used TXN number for this store.')),
                ('store', models.OneToOneField(help_text='Store this counter belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='txn_sequence', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Transaction Sequence',
                'verbose_name_plural': 'Transaction Sequences',
                'db_table': 'transactions_txnsequence',
            },
        ),
    ]
