# Generated by Django 5.2.14 on 2026-06-02 00:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('name', models.CharField(help_text="Company / vendor name, e.g. 'Bakhresa Co.'", max_length=200)),
                ('category', models.CharField(blank=True, help_text="Category of goods supplied, e.g. 'Flour / Grains'.", max_length=100)),
                ('rep', models.CharField(blank=True, help_text="Sales representative name, e.g. 'Joseph Mwangi'.", max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Primary contact phone (used for WhatsApp quick-dial).', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email for purchase orders.', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Physical or postal address.')),
                ('payment_terms', models.PositiveSmallIntegerField(choices=[(30, '30 days'), (60, '60 days'), (90, '90 days')], default=30, help_text='Standard payment terms in days: 30, 60, or 90.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_hold', 'On hold')], default='active', help_text='Active = delivering regularly; On hold = paused; Inactive = no longer used.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes — lead times, quality issues, negotiated rates.')),
                ('organisation', models.ForeignKey(help_text='Organisation (for multi-store queries).', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.organisation')),
                ('store', models.ForeignKey(help_text='Store this supplier record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('invoice_number', models.CharField(blank=True, help_text="Supplier's invoice number, e.g. 'INV-BAK-202601'.", max_length=100)),
                ('delivery_date', models.DateField(help_text='Date the goods were physically received.')),
                ('items_count', models.PositiveIntegerField(default=1, help_text='Number of line items / product types in this delivery.')),
                ('total_value', models.PositiveIntegerField(help_text='Total invoice value in TZS.')),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending'), ('partial', 'Partial')], default='delivered', help_text='Whether goods have been fully received.', max_length=20)),
                ('is_paid', models.BooleanField(default=False, help_text='True once the invoice has been fully settled.')),
                ('notes', models.TextField(blank=True, help_text='Any notes about this delivery (quality issues, shortages, etc.).')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_deliveries', to='accounts.organisation')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Staff member who logged this delivery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_deliveries', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(help_text='Store the delivery was made to.', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_deliveries', to='accounts.store')),
                ('supplier', models.ForeignKey(help_text='Supplier who made this delivery.', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Delivery',
                'verbose_name_plural': 'Supplier Deliveries',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('amount', models.PositiveIntegerField(help_text='Amount paid in TZS.')),
                ('payment_date', models.DateField(help_text='Date the payment was made.')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('mobile', 'Mobile money')], default='cash', help_text='How the payment was made.', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Bank reference, cheque number, or mobile money ID.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('delivery', models.ForeignKey(blank=True, help_text='Specific delivery this payment settles (leave blank for bulk payments).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='suppliers.supplierdelivery')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='accounts.organisation')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Staff member who logged this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='accounts.store')),
                ('supplier', models.ForeignKey(help_text='Supplier this payment was made to.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Payment',
                'verbose_name_plural': 'Supplier Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['store', 'status'], name='suppliers_s_store_i_d40f81_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdelivery',
            index=models.Index(fields=['supplier', 'is_paid'], name='suppliers_s_supplie_6748b4_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdelivery',
            index=models.Index(fields=['store', 'delivery_date'], name='suppliers_s_store_i_812c10_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'payment_date'], name='suppliers_s_supplie_efc28a_idx'),
        ),
    ]
