# Generated by Django 5.0.6 on 2026-06-03 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('name', models.CharField(help_text="Category name, e.g. 'Grocery'. Must be unique.", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what belongs in this category.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order in filter pills (0 = first).')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('name', models.CharField(help_text="Product name, e.g. 'Unga wa Sembe 10kg'.", max_length=300)),
                ('sku', models.CharField(help_text="SKU code, e.g. 'UWS-10'. Unique within a store.", max_length=50)),
                ('barcode', models.CharField(blank=True, help_text="Barcode number (EAN-13), e.g. '6160100012413'.", max_length=100)),
                ('unit', models.CharField(default='pcs', help_text='Unit of measure: pcs, bag, btl, jerry, pack, tub, etc.', max_length=20)),
                ('price', models.PositiveIntegerField(help_text='Selling price in TZS (VAT-inclusive), e.g. 28500.')),
                ('cost', models.PositiveIntegerField(help_text='Purchase / landed cost in TZS, e.g. 22000.')),
                ('stock', models.IntegerField(default=0, help_text='Current units in stock. Can go negative (oversell allowed).')),
                ('min_stock', models.PositiveIntegerField(default=0, help_text='Reorder point. Low stock alert fires when stock ≤ this value.')),
                ('max_stock', models.PositiveIntegerField(default=100, help_text='Maximum stock capacity (used for UI stock bar scale).')),
                ('weekly_sold', models.PositiveIntegerField(default=0, help_text='Average units sold per week (updated nightly).')),
                ('last_restock_at', models.DateField(blank=True, help_text='Date of the most recent stock replenishment.', null=True)),
                ('color', models.CharField(default='indigo', help_text='Color scheme key for the product avatar (indigo/amber/rose/…).', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive products are hidden from POS and inventory.')),
                ('category', models.ForeignKey(blank=True, help_text='Product category for filtering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
                ('store', models.ForeignKey(help_text='Store this product is stocked in.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.store')),
                ('supplier', models.ForeignKey(blank=True, help_text='Primary supplier / vendor for this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'unique_together': {('store', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('adjustment_type', models.CharField(choices=[('sale', 'Sale'), ('restock', 'Restock'), ('manual', 'Manual Adjustment'), ('refund', 'Refund'), ('damage', 'Damage / Write-off'), ('opening', 'Opening Stock')], help_text='What caused this stock change.', max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Units added (+) or removed (-) from stock.')),
                ('quantity_before', models.IntegerField(help_text='Stock level before this adjustment.')),
                ('quantity_after', models.IntegerField(help_text='Stock level after this adjustment.')),
                ('reference', models.CharField(blank=True, help_text='Reference document (TXN ID, PO number, etc.).', max_length=100)),
                ('note', models.TextField(blank=True, help_text='Reason for adjustment (required for manual adjustments).')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed this adjustment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product whose stock changed.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
