# Generated by Django 5.0.6 on 2026-06-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional product photo. Shown in POS grid and inventory list.",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
