# Generated by Django 5.0.6 on 2026-06-03 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('title', models.CharField(default='New conversation', help_text='Short title auto-generated from the first message.', max_length=200)),
                ('first_message_preview', models.CharField(blank=True, default='', help_text='First 200 chars of the first user message (for sidebar display).', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Archived conversations are hidden from the sidebar.')),
                ('organisation', models.ForeignKey(help_text='Organisation for AI credit billing.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='accounts.organisation')),
                ('store', models.ForeignKey(help_text='Store whose data is available to the AI in this conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='accounts.store')),
                ('user', models.ForeignKey(help_text='Staff member who started this conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'db_table': 'ai_app_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Who sent this message.', max_length=20)),
                ('content', models.TextField(help_text='Message text (Swahili or English, supports markdown).')),
                ('model_used', models.CharField(blank=True, default='', help_text="Model ID from OpenRouter (e.g. 'openai/gpt-4o-mini').", max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0, help_text='Tokens in the prompt.')),
                ('completion_tokens', models.PositiveIntegerField(default=0, help_text='Tokens in the completion.')),
                ('sources_used', models.CharField(blank=True, default='', help_text='Comma-separated list of data sources injected into context.', max_length=500)),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_app.conversation')),
            ],
            options={
                'verbose_name': 'AI Message',
                'verbose_name_plural': 'AI Messages',
                'db_table': 'ai_app_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'is_active', 'updated_at'], name='idx_conv_user_active'),
        ),
    ]
