# Generated by Django 5.0.6 on 2026-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='PK of the logged-in user.')),
                ('user_phone', models.CharField(blank=True, max_length=15)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('org_name', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Login Event',
                'verbose_name_plural': 'Login Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='tracking_lo_timesta_56ed8e_idx'), models.Index(fields=['user_id', 'timestamp'], name='tracking_lo_user_id_18ed40_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text="Request path, e.g. '/api/v1/transactions/complete-sale/'", max_length=300)),
                ('method', models.CharField(help_text='HTTP method: GET, POST, PATCH, DELETE, etc.', max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(help_text='HTTP response status code.')),
                ('user_id', models.IntegerField(blank=True, help_text='PK of the authenticated user (null if unauthenticated).', null=True)),
                ('user_phone', models.CharField(blank=True, help_text='Phone of the authenticated user (cached for display).', max_length=15)),
                ('org_name', models.CharField(blank=True, help_text='Organisation name (cached for display).', max_length=200)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Request processing time in milliseconds.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'path'], name='tracking_re_timesta_321fe4_idx'), models.Index(fields=['user_id', 'timestamp'], name='tracking_re_user_id_f1cc51_idx')],
            },
        ),
    ]
