# Generated by Django 5.0.6 on 2026-06-03 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('date', models.DateField(help_text='Calendar date (YYYY-MM-DD) for this summary.')),
                ('transaction_count', models.PositiveIntegerField(default=0, help_text='Number of transactions completed on this day.')),
                ('customer_count', models.PositiveIntegerField(default=0, help_text='Distinct registered customers who transacted on this day.')),
                ('revenue', models.PositiveIntegerField(default=0, help_text='Total revenue (paid transactions) for this day (TZS).')),
                ('credit_revenue', models.PositiveIntegerField(default=0, help_text='Revenue from credit sales for this day (TZS).')),
                ('cost_total', models.PositiveIntegerField(default=0, help_text='Total cost of goods sold on this day (TZS).')),
                ('profit', models.IntegerField(default=0, help_text='Gross profit (total - cost - tax) for this day (TZS).')),
                ('tax_collected', models.PositiveIntegerField(default=0, help_text='Total VAT collected on this day (TZS).')),
                ('refund_total', models.PositiveIntegerField(default=0, help_text='Total refunded on this day (TZS).')),
                ('cash_revenue', models.PositiveIntegerField(default=0, help_text='Revenue from Cash payments (TZS).')),
                ('mpesa_revenue', models.PositiveIntegerField(default=0, help_text='Revenue from M-Pesa payments (TZS).')),
                ('tigo_revenue', models.PositiveIntegerField(default=0, help_text='Revenue from Tigo Pesa payments (TZS).')),
                ('bank_revenue', models.PositiveIntegerField(default=0, help_text='Revenue from Bank payments (TZS).')),
                ('credit_issued', models.PositiveIntegerField(default=0, help_text='Amount issued on credit this day (TZS).')),
                ('store', models.ForeignKey(help_text='The store this summary belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Daily Summary',
                'verbose_name_plural': 'Daily Summaries',
                'db_table': 'analytics_dailysummary',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['store', 'date'], name='idx_daily_store_date')],
                'unique_together': {('store', 'date')},
            },
        ),
    ]
