# Generated by Django 5.0.6 on 2026-06-03 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('report_type', models.CharField(choices=[('sales', 'Sales Summary'), ('inventory', 'Inventory Valuation'), ('tax', 'Tax Statement'), ('credit', 'Credit Aged Debtors')], help_text='Which report to generate: sales, inventory, tax, or credit.', max_length=20)),
                ('name', models.CharField(help_text="Human-readable name shown in the UI, e.g. 'Daily Sales Summary'.", max_length=200)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='How often to run: daily, weekly, or monthly.', max_length=10)),
                ('date_range_preset', models.CharField(choices=[('7d', 'Last 7 days'), ('30d', 'Last 30 days'), ('90d', 'Last 90 days'), ('month', 'This calendar month'), ('ytd', 'Year to date')], default='30d', help_text="Date range to include in the report. 'month' means the completed calendar month; '7d' means the 7 days preceding the send date.", max_length=10)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to send the report to.')),
                ('is_enabled', models.BooleanField(default=True, help_text='When False, this schedule is paused and will not be auto-sent. Toggled via the switch in the UI.')),
                ('last_sent_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful delivery.', null=True)),
                ('next_send_at', models.DateTimeField(blank=True, help_text='When the next send will happen. Calculated by the management command after each dispatch.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who set up this scheduled report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(help_text='Organisation (for multi-store scoping).', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='accounts.organisation')),
                ('store', models.ForeignKey(help_text='Store this scheduled report belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('report_type', models.CharField(choices=[('sales', 'Sales Summary'), ('inventory', 'Inventory Valuation'), ('tax', 'Tax Statement'), ('credit', 'Credit Aged Debtors')], help_text='Which report type was generated.', max_length=20)),
                ('name', models.CharField(help_text="Display name shown in history, e.g. 'Sales Summary'.", max_length=200)),
                ('period_label', models.CharField(help_text="Human-readable period label, e.g. '1 – 24 May 2026'.", max_length=100)),
                ('date_from', models.DateField(help_text='Start date of the report period (inclusive).')),
                ('date_to', models.DateField(help_text='End date of the report period (inclusive).')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON / PDF')], default='csv', help_text='Export format: csv or json.', max_length=10)),
                ('file_size_bytes', models.PositiveIntegerField(default=0, help_text='Approximate file size in bytes (for display in history table).')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who generated the export (null for auto-scheduled exports).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(help_text='Organisation (for multi-store scoping).', on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='accounts.organisation')),
                ('store', models.ForeignKey(help_text='Store the report was generated for.', on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='accounts.store')),
                ('scheduled_report', models.ForeignKey(blank=True, help_text='The scheduled report that triggered this export (null for manual exports).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='reports.scheduledreport')),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['store', 'is_enabled'], name='reports_sch_store_i_7557f6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['store', 'report_type'], name='reports_rep_store_i_527388_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['store', 'created_at'], name='reports_rep_store_i_4eb3a7_idx'),
        ),
    ]
