# Generated by Django 5.0.6 on 2026-07-19 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_organisation_sendafrica_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('title', models.CharField(help_text='Description / name of this expense.', max_length=255)),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Salaries', 'Salaries'), ('Supplies', 'Supplies'), ('Transport', 'Transport'), ('Marketing', 'Marketing'), ('Maintenance', 'Maintenance'), ('Licences & permits', 'Licences & permits'), ('Insurance', 'Insurance'), ('Other', 'Other')], default='Other', help_text='Expense category.', max_length=50)),
                ('amount', models.PositiveIntegerField(help_text='Expense amount in TZS.')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Tigo Pesa', 'Tigo Pesa'), ('Bank', 'Bank'), ('Airtel Money', 'Airtel Money')], default='Cash', help_text='Method used for this payment.', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', help_text='Receipt or reference number.', max_length=100)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes / description.')),
                ('receipt_url', models.URLField(blank=True, default='', help_text='Link to a receipt photo.', max_length=500)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Staff member who recorded this expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(help_text='Store where this expense was recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses_expense',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'category'], name='idx_exp_store_cat'), models.Index(fields=['store', 'payment_method'], name='idx_exp_pay_meth'), models.Index(fields=['store', 'created_at'], name='idx_exp_store_date')],
            },
        ),
    ]
