# Generated by Django 5.0.6 on 2026-06-03 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated (UTC).')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 (poor) to 5 (excellent).')),
                ('title', models.CharField(blank=True, default='', help_text='Short headline for the review.', max_length=200)),
                ('body', models.TextField(blank=True, default='', help_text='Full review text.')),
                ('business_type_display', models.CharField(blank=True, default='', help_text='Human-readable business type, copied from org on creation.', max_length=100)),
                ('region_display', models.CharField(blank=True, default='', help_text='Region, copied from org on creation.', max_length=100)),
                ('trigger', models.CharField(blank=True, default='manual', help_text='Which trigger generated this review prompt.', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Only public reviews appear on the landing page.')),
                ('organisation', models.ForeignKey(help_text='Organisation that submitted this review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.organisation')),
                ('reviewer', models.ForeignKey(blank=True, help_text='User who submitted the review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Review',
                'verbose_name_plural': 'Store Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
